name: Test Gen

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Doxygen
      run: sudo apt-get install -y doxygen

    - name: Generate Doxygen_doc
      run: doxygen Doxyfile

    - name: Create gh-pages branch (if not exists)
      run: |
        if ! git ls-remote --exit-code origin gh-pages; then
          git checkout --orphan gh-pages
          git reset --hard
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit --allow-empty -m "Initialize gh-pages branch"
          git push origin gh-pages
        fi

    - name: Deploy to GitHub
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PAT }}
        publish_dir: ./docs/html
